sudo: required
dist: xenial
env:
  - PY=e ANGR_REPO=angr
  - PY=e ANGR_REPO=angr-platforms
  - PY=e ANGR_REPO=angr-doc
  - PY=e ANGR_REPO=angrop
  - PY=e ANGR_REPO=fuzzer
  - PY=e ANGR_REPO=driller
  - PY=p ANGR_REPO=colorguard
  - PY=e ANGR_REPO=fidget
  - PY=e ANGR_REPO=patcherex
  - PY=e ANGR_REPO=tracer NOSE_OPTIONS="--process-timeout=900"
  - PY=p ANGR_REPO=rex
  - PY=e ANGR_REPO=heaphopper
install: ( curl https://raw.githubusercontent.com/angr/angr-dev/$TRAVIS_BRANCH/tests/travis-install.sh | grep -v 404 || curl https://raw.githubusercontent.com/angr/angr-dev/master/tests/travis-install.sh ) | bash
script: ~/angr-dev/tests/travis-test.sh
notifications:
  slack:
    secure: PMVmylQ0ixCTr4LDPlKpbDFUWt9u6vgnmpJi9OfV+M8UBI4ZfCxHo/aZNMKaWzOrOSfKtXx5sCFVmF469N0OYNy1L76AWjDImiqJtbxK8n5ABz4Udc6UVRzctBL1SHxffay7pLJmiMqw1OSOPkm8PDah06dGjGZNyOLe0T4DOIF4fM/Li4gXhZla9KtHtt2K1yNKlDhgDJmYpnwsYnIRd48UhHjwDgCzKOIh6dsLYg1QFYMvZ32IkrcCGUnR0IfcIBy3+wVun5IK4MtlVgkz6F4q3jw3Jl6j5w20D2pxyfBew5d8yIBziekywgAKsVZuH9gJuUI769FYoR0lIspB+rhqWt+c7c9T+WQCPBoPgEZW5muBlbBcezmQG9/CvTE2sEJJDcCWWk4YPuqnqDvYwoPmts+OKekjCGilHGHdI7mLz2Yp1StxSmwKC710DDGB1h9lt77If2j1AdrmJviTcEL/qW0Nq7HpKT0dfGDb6SxpWiXqHNjcKB/xpDK9trAZ1P6fdILNXOzUAtTcrvIMUWNGU+5ci7PSpcXU/jyuXrCPPFzYo/aMENvKz4ay5SOyqpv6FS9lndtdWARpn4Uc6mFWN3omhh4KKwDpSA38wOhB2IO8Fsk7d5KSTskR357D+NA5A/MkRqpKfFDdINpNNf0rVlnSUc5bejcXb2Pwi7Q=
