language: python
python: 2.7
sudo: required
dist: xenial
env:
  - PY=e ANGR_REPO=simuvex
  - PY=e ANGR_REPO=angr
  - PY=e ANGR_REPO=angr-doc
  - PY=e ANGR_REPO=angrop
  - PY=e ANGR_REPO=fuzzer
  - PY=e ANGR_REPO=driller
  - PY=p ANGR_REPO=colorguard
  - PY=e ANGR_REPO=fidget
  - PY=e ANGR_REPO=patcherex
#  - PY=e ANGR_REPO=tracer NOSE_OPTIONS="-x" NOSE_PROCESSES=1
#  - PY=p ANGR_REPO=rex NOSE_OPTIONS="-x" NOSE_PROCESSES=1
install: ( curl https://raw.githubusercontent.com/angr/angr-dev/$TRAVIS_BRANCH/travis-install.sh | grep -v 404 || curl https://raw.githubusercontent.com/angr/angr-dev/master/travis-install.sh ) | bash
script: ~/angr-dev/travis-test.sh
