[package]
name = "angr"
version = "0.1.0"
edition = "2024"

[lib]
name = "rustylib"
crate-type = ["cdylib"]

[dependencies]
backtrace = "0.3.76"
icicle-fuzzing = { git = "https://github.com/icicle-emu/icicle-emu.git", rev = "6040b08d23e8690b98f950cff5847fe5daa093f7" }
icicle-vm = { git = "https://github.com/icicle-emu/icicle-emu.git", rev = "6040b08d23e8690b98f950cff5847fe5daa093f7" }
libafl = { version = "0.15.4" }
libafl_bolts = { version = "0.15.4" }
pcode = { git = "https://github.com/icicle-emu/icicle-emu.git", rev = "6040b08d23e8690b98f950cff5847fe5daa093f7" }
postcard = { version = "1.1.3", default-features = false, features = ["use-std"] }
pyo3 = { version = "0.27.2", features = ["py-clone"] }
rangemap = "1.7.1"
send_wrapper = "0.6.0"
serde = { version = "1.0.228", features = ["derive"] }
target-lexicon = "0.13.4"

[dev-dependencies]
tempfile = "3.24.0"
