[package]
name = "angr"
version = "0.1.0"
edition = "2024"

[lib]
name = "rustylib"
crate-type = ["cdylib"]

[dependencies]
backtrace = "0.3.75"
icicle-fuzzing = { git = "https://github.com/icicle-emu/icicle-emu.git", rev = "4d7ed93254a20b7e5c16bd7b0c6b46db49e1c72e" }
icicle-vm = { git = "https://github.com/icicle-emu/icicle-emu.git", rev = "4d7ed93254a20b7e5c16bd7b0c6b46db49e1c72e" }
libafl = { version = "0.15.3", default-features = false, features = ["errors_backtrace"]}
libafl_bolts = { version = "0.15.3" }
pcode = { git = "https://github.com/icicle-emu/icicle-emu.git", rev = "4d7ed93254a20b7e5c16bd7b0c6b46db49e1c72e" }
postcard = { version = "1.1.3", default-features = false, features = ["use-std"] }
pyo3 = { version = "0.27.2", features = ["py-clone"] }
rangemap = "1.7.1"
send_wrapper = "0.6.0"
serde = { version = "1.0.219", features = ["derive"] }
target-lexicon = "0.12.16"
